export const upcomingEvents = [
  {
    id: "1",
    title: "Quantum Computing Workshop",
    date: "2026-03-15T10:00:00",
    location: "Auditorium A",
    category: "Workshop",
    description: "Explore the fundamentals of quantum computing with hands-on labs and expert speakers.",
    image: "quantum",
    registrations: 87,
    maxCapacity: 120,
  },
  {
    id: "2",
    title: "AI/ML Hackathon 2026",
    date: "2026-04-01T09:00:00",
    location: "Innovation Lab",
    category: "Hackathon",
    description: "48-hour hackathon focused on building AI/ML solutions for real-world problems.",
    image: "hackathon",
    registrations: 156,
    maxCapacity: 200,
  },
  {
    id: "3",
    title: "Women in Tech Summit",
    date: "2026-03-22T14:00:00",
    location: "Main Hall",
    category: "Summit",
    description: "Celebrating women leaders in technology with keynotes and panel discussions.",
    image: "summit",
    registrations: 210,
    maxCapacity: 300,
  },
  {
    id: "4",
    title: "Cybersecurity Bootcamp",
    date: "2026-04-10T11:00:00",
    location: "Lab 3",
    category: "Bootcamp",
    description: "Intensive cybersecurity training covering ethical hacking and defense strategies.",
    image: "cyber",
    registrations: 45,
    maxCapacity: 60,
  },
  {
    id: "5",
    title: "IoT Innovation Challenge",
    date: "2026-05-05T10:00:00",
    location: "Tech Park",
    category: "Competition",
    description: "Design and prototype IoT solutions for smart campus applications.",
    image: "iot",
    registrations: 72,
    maxCapacity: 100,
  },
];

export const recruitmentRoles = [
  {
    id: "1",
    title: "Technical Lead",
    team: "Core Technical",
    description: "Lead technical projects and mentor team members in cutting-edge technologies.",
    skills: ["React", "Node.js", "System Design"],
    eligibility: "2nd/3rd Year",
    openings: 2,
    status: "open" as const,
  },
  {
    id: "2",
    title: "Design Head",
    team: "Creative",
    description: "Oversee all visual identity and design systems for IEEE IGDTUW.",
    skills: ["Figma", "UI/UX", "Branding"],
    eligibility: "2nd/3rd Year",
    openings: 1,
    status: "open" as const,
  },
  {
    id: "3",
    title: "Content Writer",
    team: "Editorial",
    description: "Craft compelling content for events, social media, and newsletters.",
    skills: ["Writing", "SEO", "Social Media"],
    eligibility: "1st/2nd Year",
    openings: 3,
    status: "open" as const,
  },
  {
    id: "4",
    title: "Event Coordinator",
    team: "Operations",
    description: "Plan and execute large-scale technical events and workshops.",
    skills: ["Management", "Communication", "Planning"],
    eligibility: "Any Year",
    openings: 4,
    status: "open" as const,
  },
  {
    id: "5",
    title: "ML Research Intern",
    team: "Research",
    description: "Contribute to ongoing machine learning research projects.",
    skills: ["Python", "TensorFlow", "Research"],
    eligibility: "3rd/4th Year",
    openings: 2,
    status: "closed" as const,
  },
];

export const galleryImages = [
  { id: "1", title: "CodeStorm Hackathon 2025", category: "Hackathons", year: 2025, image: "hackathon-1", description: "48-hour coding marathon with 200+ participants" },
  { id: "2", title: "AI/ML Workshop Series", category: "Workshops", year: 2025, image: "workshop-1", description: "Hands-on machine learning with TensorFlow" },
  { id: "3", title: "Tech Talk: Future of Quantum Computing", category: "Tech Talks", year: 2025, image: "tech-talk-1", description: "Industry expert insights on quantum tech" },
  { id: "4", title: "Robotics Competition", category: "Robotics", year: 2025, image: "robotics-1", description: "Autonomous robot design challenge" },
  { id: "5", title: "AI Ethics Symposium", category: "AI Events", year: 2025, image: "ai-event-1", description: "Exploring ethical AI development" },
  { id: "6", title: "Networking Mixer 2025", category: "Networking", year: 2025, image: "networking-1", description: "Industry professionals meet students" },
  { id: "7", title: "Blockchain Workshop", category: "Workshops", year: 2024, image: "workshop-2", description: "Smart contracts and DApp development" },
  { id: "8", title: "GameDev Jam", category: "Hackathons", year: 2024, image: "hackathon-2", description: "Game development competition" },
  { id: "9", title: "Cloud Architecture Talk", category: "Tech Talks", year: 2024, image: "tech-talk-2", description: "AWS and Azure best practices" },
  { id: "10", title: "Drone Programming Workshop", category: "Robotics", year: 2024, image: "robotics-2", description: "Autonomous flight programming" },
  { id: "11", title: "Computer Vision Summit", category: "AI Events", year: 2024, image: "ai-event-2", description: "Latest advances in CV technology" },
  { id: "12", title: "Alumni Networking Night", category: "Networking", year: 2024, image: "networking-2", description: "Connect with IEEE alumni" },
  { id: "13", title: "IoT Hackathon", category: "Hackathons", year: 2023, image: "hackathon-3", description: "Internet of Things innovation challenge" },
  { id: "14", title: "Cybersecurity Workshop", category: "Workshops", year: 2023, image: "workshop-3", description: "Ethical hacking and defense strategies" },
  { id: "15", title: "Startup Pitch Session", category: "Tech Talks", year: 2023, image: "tech-talk-3", description: "Student startup presentations" },
  { id: "16", title: "Autonomous Vehicles Demo", category: "Robotics", year: 2023, image: "robotics-3", description: "Self-driving car technology showcase" },
  { id: "17", title: "NLP Conference", category: "AI Events", year: 2023, image: "ai-event-3", description: "Natural language processing advances" },
  { id: "18", title: "Career Fair 2023", category: "Networking", year: 2023, image: "networking-3", description: "Tech company recruitment event" },
];

export const membershipBenefits = [
  { icon: "BookOpen", title: "IEEE Xplore Access", description: "Access millions of research papers and publications." },
  { icon: "Users", title: "Global Network", description: "Connect with 400,000+ members worldwide." },
  { icon: "Award", title: "Competitions", description: "Participate in exclusive IEEE competitions and challenges." },
  { icon: "Briefcase", title: "Career Resources", description: "Job boards, mentorship, and career development tools." },
  { icon: "Zap", title: "Workshops", description: "Free or discounted access to technical workshops and conferences." },
  { icon: "Shield", title: "Certifications", description: "Industry-recognized certificates and skill validation." },
];

export const timelineMilestones = [
  { year: 2018, title: "IEEE IGDTUW Founded", description: "Student branch established with 30 founding members." },
  { year: 2019, title: "First Hackathon", description: "Hosted CodeStorm with 200+ participants." },
  { year: 2020, title: "Virtual Pivot", description: "Successfully transitioned to online events during the pandemic." },
  { year: 2021, title: "500 Members", description: "Crossed 500 active members milestone." },
  { year: 2022, title: "National Recognition", description: "Won Best IEEE Student Branch Award — North India." },
  { year: 2023, title: "Research Wing Launch", description: "Started an ML/AI research wing with published papers." },
  { year: 2024, title: "1000 Members", description: "Reached 1000 active members across all years." },
  { year: 2025, title: "International Collaboration", description: "Partnered with IEEE chapters in 5 countries." },
];

export const profileData = {
  name: "Astronaut",
  email: "explorer@igdtuw.ac.in",
  memberId: "IEEE-2026-0042",
  joinedDate: "2025-08-15",
  eventsAttended: 12,
  savedEvents: ["1", "3", "5"],
  avatar: "planet-1",
  points: 850,
  hours: 156,
};
